"""Join TodoList tale to Todo via FoerignKey constraint

Revision ID: 03771e50bb5e
Revises: 9f6a1c5601d1
Create Date: 2022-05-21 02:48:55.895665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03771e50bb5e'
down_revision = '9f6a1c5601d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    # ### end Alembic commands ###
