"""Add name column to TodoList

A todolist must have a name/category

Revision ID: 27bb8914a3e0
Revises: 1172b8c130ae
Create Date: 2022-05-21 03:12:08.494120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27bb8914a3e0'
down_revision = '1172b8c130ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'name')
    # ### end Alembic commands ###
