"""Initial migration

Revision ID: 6e651022318f
Revises: 
Create Date: 2022-05-18 15:26:04.171051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e651022318f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("completed", sa.Boolean(), nullable=True))
    op.execute("update todos set completed = False where completed is null")
    op.alter_column("todos", sa.Column("completed", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "completed")
    # ### end Alembic commands ###
